name: R-CMD-check

on:
  push:
    branches: 
      - unit-test
  pull_request:
    branches: 
      - unit-test

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        install.packages(c("devtools", "roxygen2", "testthat", "dplyr", "rlang", "rcmdcheck"))
        devtools::install_deps(dependencies = TRUE)
      shell: Rscript {0}

    - name: Check package
      run: R CMD check .

    - name: Run tests
      run: Rscript -e 'devtools::test()'